//
//  MockupData.swift
//  MyGarden
//
//  Created by Filipe Marques on 13/06/19.
//  Copyright © 2019 Filipe Marques. All rights reserved.
//

import UIKit

struct Crop {
    var name:String
    var image:UIImage
    var tempRangeStart:Int
    var tempRangeEnd:Int
    var lumRangeStart:Int
    var lumRangeEnd:Int
    var humRangeStart:Int
    var humRangeEnd:Int
    var isCollapsed:Bool
}

class MockupData: NSObject {
    static var crops:[Crop] = [
        Crop(name: "Maçã",
             image: UIImage(named: "Apple")!,
             tempRangeStart: 21,
             tempRangeEnd: 27,
             lumRangeStart: 100,
             lumRangeEnd: 700,
             humRangeStart: 25,
             humRangeEnd: 55,
             isCollapsed: true),
        Crop(name: "Abacate",
             image: UIImage(named: "Avocado")!,
             tempRangeStart: 21,
             tempRangeEnd: 27,
             lumRangeStart: 100,
             lumRangeEnd: 700,
             humRangeStart: 25,
             humRangeEnd: 55,
             isCollapsed: true),
        Crop(name: "Banana",
             image: UIImage(named: "Banana")!,
             tempRangeStart: 21,
             tempRangeEnd: 27,
             lumRangeStart: 100,
             lumRangeEnd: 700,
             humRangeStart: 25,
             humRangeEnd: 55,
             isCollapsed: true),
        Crop(name: "Beterraba",
             image: UIImage(named: "Beet")!,
             tempRangeStart: 21,
             tempRangeEnd: 27,
             lumRangeStart: 100,
             lumRangeEnd: 700,
             humRangeStart: 25,
             humRangeEnd: 55,
             isCollapsed: true),
        Crop(name: "Brócolis",
             image: UIImage(named: "Broccoli")!,
             tempRangeStart: 21,
             tempRangeEnd: 27,
             lumRangeStart: 100,
             lumRangeEnd: 700,
             humRangeStart: 25,
             humRangeEnd: 55,
             isCollapsed: true),
        Crop(name: "Cenoura",
             image: UIImage(named: "Carrot")!,
             tempRangeStart: 21,
             tempRangeEnd: 27,
             lumRangeStart: 100,
             lumRangeEnd: 700,
             humRangeStart: 25,
             humRangeEnd: 55,
             isCollapsed: true),
        Crop(name: "Pimenta",
             image: UIImage(named: "Pepper")!,
             tempRangeStart: 21,
             tempRangeEnd: 27,
             lumRangeStart: 100,
             lumRangeEnd: 700,
             humRangeStart: 25,
             humRangeEnd: 55,
             isCollapsed: true),
        Crop(name: "Limão",
             image: UIImage(named: "Citrus")!,
             tempRangeStart: 21,
             tempRangeEnd: 27,
             lumRangeStart: 100,
             lumRangeEnd: 700,
             humRangeStart: 25,
             humRangeEnd: 55,
             isCollapsed: true),
        Crop(name: "Milho",
             image: UIImage(named: "Corn")!,
             tempRangeStart: 21,
             tempRangeEnd: 27,
             lumRangeStart: 100,
             lumRangeEnd: 700,
             humRangeStart: 25,
             humRangeEnd: 55,
             isCollapsed: true),
        Crop(name: "Cebola",
             image: UIImage(named: "Onion")!,
             tempRangeStart: 21,
             tempRangeEnd: 27,
             lumRangeStart: 100,
             lumRangeEnd: 700,
             humRangeStart: 25,
             humRangeEnd: 55,
             isCollapsed: true),
        Crop(name: "Pimentão",
             image: UIImage(named: "Paprika")!,
             tempRangeStart: 21,
             tempRangeEnd: 27,
             lumRangeStart: 100,
             lumRangeEnd: 700,
             humRangeStart: 25,
             humRangeEnd: 55,
             isCollapsed: true),
        Crop(name: "Pêssego",
             image: UIImage(named: "Peach")!,
             tempRangeStart: 21,
             tempRangeEnd: 27,
             lumRangeStart: 100,
             lumRangeEnd: 700,
             humRangeStart: 25,
             humRangeEnd: 55,
             isCollapsed: true),
        Crop(name: "Pêra",
             image: UIImage(named: "Pear")!,
             tempRangeStart: 21,
             tempRangeEnd: 27,
             lumRangeStart: 100,
             lumRangeEnd: 700,
             humRangeStart: 25,
             humRangeEnd: 55,
             isCollapsed: true),
        Crop(name: "Abacaxi",
             image: UIImage(named: "Pineapple")!,
             tempRangeStart: 21,
             tempRangeEnd: 27,
             lumRangeStart: 100,
             lumRangeEnd: 700,
             humRangeStart: 25,
             humRangeEnd: 55,
             isCollapsed: true),
        Crop(name: "Romã",
             image: UIImage(named: "Pomegranate")!,
             tempRangeStart: 21,
             tempRangeEnd: 27,
             lumRangeStart: 100,
             lumRangeEnd: 700,
             humRangeStart: 25,
             humRangeEnd: 55,
             isCollapsed: true),
        Crop(name: "Soja",
             image: UIImage(named: "Soy")!,
             tempRangeStart: 21,
             tempRangeEnd: 27,
             lumRangeStart: 100,
             lumRangeEnd: 700,
             humRangeStart: 25,
             humRangeEnd: 55,
             isCollapsed: true),
        Crop(name: "Morango",
             image: UIImage(named: "Strawberry")!,
             tempRangeStart: 21,
             tempRangeEnd: 27,
             lumRangeStart: 100,
             lumRangeEnd: 700,
             humRangeStart: 25,
             humRangeEnd: 55,
             isCollapsed: true),
        Crop(name: "Tomate",
             image: UIImage(named: "Tomato")!,
             tempRangeStart: 21,
             tempRangeEnd: 27,
             lumRangeStart: 100,
             lumRangeEnd: 700,
             humRangeStart: 25,
             humRangeEnd: 55,
             isCollapsed: true),
        Crop(name: "Melancia",
             image: UIImage(named: "Watermelon")!,
             tempRangeStart: 21,
             tempRangeEnd: 27,
             lumRangeStart: 100,
             lumRangeEnd: 700,
             humRangeStart: 25,
             humRangeEnd: 55,
             isCollapsed: true)
    ]
}

